name: APIM Deploy (Only Changed APIs)

on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'
      - 'deploy/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run APIM Deployment Script
      env:
        APIM_RESOURCE_GROUP: ${{ secrets.APIM_RESOURCE_GROUP }}
        APIM_NAME: ${{ secrets.APIM_NAME }}
      run: |
        chmod +x ./deploy/*.sh
        ./deploy/script.sh
